const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");
const FntParser = require("../src/core/fntParser.js");
const { layoutText } = require("../src/core/layout.js");

// samples/demo.fnt is generated by tools/make-demo-font.js
const load = () =>
  FntParser.parse(fs.readFileSync(path.join(__dirname, "..", "samples", "demo.fnt"), "utf8"));

test("parser reads the text format", () => {
  const f = load();
  assert.strictEqual(f.info.face, "demo");
  assert.strictEqual(f.common.lineHeight, 54);
  assert.strictEqual(f.pages[0], "demo.png");
  assert.strictEqual(Object.keys(f.chars).length, 15);
  assert.deepStrictEqual(
    { x: f.chars[49].x, y: f.chars[49].y, w: f.chars[49].width, xadv: f.chars[49].xadvance },
    { x: 34, y: 2, w: 30, xadv: 30 }
  );
});

test("parser reads kernings", () => {
  const f = FntParser.parse(
    'common lineHeight=10 base=8\npage id=0 file="a.png"\nchar id=65 x=0 y=0 width=5 height=5 xoffset=0 yoffset=0 xadvance=6\nkerning first=65 second=86 amount=-2'
  );
  assert.strictEqual(FntParser.kerningFor(f, 65, 86), -2);
  assert.strictEqual(FntParser.kerningFor(f, 86, 65), 0);
});

test("parser reads BMFont XML (multi-page) and rejects binary/garbage", () => {
  const xml = '<?xml version="1.0"?><font><info face="X" size="10"/><common lineHeight="12" base="9" scaleW="64" scaleH="64" pages="2" packed="0"/>' +
    '<pages><page id="0" file="a.png"/><page id="1" file="b c.png"/></pages><chars count="2">' +
    '<char id="65" x="1" y="2" width="3" height="4" xoffset="0" yoffset="1" xadvance="5" page="1" chnl="15"/>' +
    '<char id="66" x="1" y="2" width="3" height="4" xoffset="0" yoffset="1" xadvance="5" page="0" chnl="15"/></chars>' +
    '<kernings count="1"><kerning first="65" second="66" amount="-1"/></kernings></font>';
  const f = FntParser.parse(xml);
  assert.deepStrictEqual(f.pages, ["a.png", "b c.png"]);
  assert.strictEqual(f.chars[65].page, 1);
  assert.strictEqual(f.info.face, "X");
  assert.strictEqual(FntParser.kerningFor(f, 65, 66), -1);
  const r = layoutText(f, "AB");
  assert.deepStrictEqual(r.glyphs.map((g) => g.page), [1, 0]);
  assert.throws(() => FntParser.parse("BMF\u0003binary"), /binary/);
  assert.throws(() => FntParser.parse("garbage"), /Invalid/);
});

test("layout: the cursor advances by xadvance", () => {
  const f = load();
  const r = layoutText(f, "1250");
  assert.strictEqual(r.glyphs.length, 4);
  assert.strictEqual(r.glyphs[0].x, f.chars[49].xoffset);
  assert.strictEqual(r.glyphs[1].x, 30 + f.chars[50].xoffset);
  assert.strictEqual(r.glyphs[3].x, 30 * 3 + f.chars[48].xoffset);
  assert.strictEqual(r.width, 30 * 4);
});

test("layout: spaces advance without a glyph; tracking and scale", () => {
  const f = load();
  const r = layoutText(f, "1 2", { scale: 2, tracking: 3 });
  assert.strictEqual(r.glyphs.length, 2);
  // cursor after '1' = (30+3)*2; after the space = +(14+3)*2
  assert.strictEqual(r.glyphs[1].x, (30 + 3) * 2 + (14 + 3) * 2 + f.chars[50].xoffset * 2);
});

test("layout: missing characters and multiple lines", () => {
  const f = load();
  const r = layoutText(f, "1\nA2");
  assert.deepStrictEqual(r.missing, ["A"]);
  assert.strictEqual(r.glyphs.length, 2);
  assert.strictEqual(r.glyphs[1].y, 54 + f.chars[50].yoffset);
  assert.strictEqual(r.height, 54 * 2);
});

test("layout: per-letter overrides", () => {
  const f = load();
  const r = layoutText(f, "12", { overrides: { 1: { kern: 5, dy: -4 } } });
  assert.strictEqual(r.glyphs[1].x, 30 + 5 + f.chars[50].xoffset);
  assert.strictEqual(r.glyphs[1].y, f.chars[50].yoffset - 4);
});

test("layout is linear in scale/tracking/line height (basis of the AE expressions)", () => {
  const f = load();
  const ov = { 1: { kern: 3, dy: 2, scale: 1.5 } };
  const s = 1.7, t = 4, lh = 150, text = "12\n50";
  const base = layoutText(f, text, { scale: 1, tracking: 0, lineHeight: 0, overrides: ov });
  const cur = layoutText(f, text, { scale: s, tracking: t, lineHeight: lh, overrides: ov });
  const widest = base.counts.indexOf(Math.max(...base.counts));
  const Nw = base.counts[widest];
  cur.glyphs.forEach((g, i) => {
    const b = base.glyphs[i];
    const cx = g.x + g.w / 2 - cur.width / 2;
    const cy = g.y + g.h / 2 - cur.height / 2;
    const px = s * (b.x + b.w / 2 - base.width / 2 + t * (g.n - (Nw - 1) / 2));
    const py = s * (b.y + b.h / 2 + (g.line - cur.lines / 2) * lh);
    assert.ok(Math.abs(cx - px) < 1e-9, "x " + i);
    assert.ok(Math.abs(cy - py) < 1e-9, "y " + i);
  });
});
